# ==============================================================================
# Interactive R Shiny Dashboard
# Project Title: Crime Pattern Analysis and Crime Risk Prediction in India using Machine Learning
# ==============================================================================

suppressPackageStartupMessages({
  library(shiny)
  library(shinydashboard)
  library(bslib)
  library(ggplot2)
  library(dplyr)
  library(readr)
  library(plotly)
})

# Register local directory resource paths for images and output files
addResourcePath("Graphs", "Graphs")
addResourcePath("Output", "Output")

# Load existing datasets generated by the R scripts
cleaned_data <- read_csv("Output/cleaned_crime_data.csv", show_col_types = FALSE)
model_results <- read_csv("Output/model_results.csv", show_col_types = FALSE)
predictions_data <- read_csv("Output/predictions.csv", show_col_types = FALSE)

# Format factor levels
cleaned_data$Crime_Risk <- factor(cleaned_data$Crime_Risk, levels = c("Low", "Medium", "High"))

# Custom dark / glassmorphism theme
custom_theme <- bs_theme(
  version = 5,
  bg = "#071426",
  fg = "#EAF2FF",
  primary = "#6C63FF",
  secondary = "#A855F7",
  success = "#20E3B2",
  info = "#38BDF8",
  warning = "#FBBF24",
  danger = "#FB5B7A",
  base_font = font_google("Inter")
)

# Shared dark-dashboard styling
dark_css <- tags$head(
  tags$style(HTML("
    :root {
      --bg: #071426;
      --panel: rgba(12, 30, 57, .88);
      --panel2: rgba(18, 39, 72, .92);
      --line: rgba(108, 99, 255, .35);
      --text: #EAF2FF;
      --muted: #9FB2CF;
      --purple: #8B5CF6;
      --blue: #38BDF8;
      --cyan: #22D3EE;
      --teal: #20E3B2;
      --pink: #FB5B9A;
      --gold: #FBBF24;
    }

    html, body {
      background:
        radial-gradient(circle at 10% 0%, rgba(76, 29, 149, .28), transparent 28%),
        radial-gradient(circle at 90% 10%, rgba(14, 116, 144, .22), transparent 25%),
        #071426 !important;
      color: var(--text) !important;
      min-height: 100%;
    }

    .navbar {
      background:
        linear-gradient(105deg, #081A36 0%, #111C4D 48%, #24104A 100%) !important;
      border-bottom: 1px solid rgba(139, 92, 246, .55) !important;
      box-shadow: 0 8px 30px rgba(0,0,0,.38) !important;
      padding-top: 7px !important;
      padding-bottom: 7px !important;
    }

    .navbar-brand {
      color: #FFFFFF !important;
      font-weight: 800 !important;
      letter-spacing: .25px;
      text-shadow: 0 0 18px rgba(139,92,246,.45);
    }

    .navbar .nav-link {
      color: #C9D8F2 !important;
      border-radius: 11px !important;
      margin: 3px 4px !important;
      transition: all .22s ease !important;
      font-weight: 650 !important;
    }

    .navbar .nav-link:hover {
      color: #FFFFFF !important;
      background: linear-gradient(135deg, rgba(108,99,255,.30), rgba(56,189,248,.18)) !important;
      transform: translateY(-2px);
      box-shadow: 0 6px 18px rgba(108,99,255,.20);
    }

    .navbar .nav-link.active {
      color: #FFFFFF !important;
      background: linear-gradient(135deg, #4F46E5, #7C3AED) !important;
      box-shadow: 0 7px 22px rgba(99,102,241,.42) !important;
    }

    .container-fluid {
      max-width: 1600px;
    }

    .card {
      background: linear-gradient(145deg, rgba(15,36,68,.94), rgba(8,24,46,.96)) !important;
      color: var(--text) !important;
      border: 1px solid rgba(94, 164, 255, .20) !important;
      border-radius: 18px !important;
      box-shadow:
        0 12px 30px rgba(0,0,0,.32),
        inset 0 1px 0 rgba(255,255,255,.035) !important;
      overflow: hidden !important;
      transition: transform .20s ease, box-shadow .20s ease, border-color .20s ease !important;
    }

    .card:hover {
      transform: translateY(-3px);
      border-color: rgba(139,92,246,.52) !important;
      box-shadow:
        0 18px 38px rgba(0,0,0,.40),
        0 0 25px rgba(108,99,255,.10),
        inset 0 1px 0 rgba(255,255,255,.05) !important;
    }

    .card-header {
      background: linear-gradient(90deg, rgba(30,48,88,.88), rgba(37,23,76,.72)) !important;
      color: #F5F8FF !important;
      border-bottom: 1px solid rgba(139,92,246,.25) !important;
      font-weight: 750 !important;
      padding: 13px 17px !important;
    }

    .card-body {
      color: var(--text) !important;
    }

    .value-box {
      min-height: 132px !important;
      border: 1px solid rgba(255,255,255,.12) !important;
      border-radius: 18px !important;
      box-shadow: 0 12px 26px rgba(0,0,0,.30) !important;
      transition: all .22s ease !important;
      overflow: hidden !important;
      position: relative !important;
    }

    .value-box:hover {
      transform: translateY(-6px) scale(1.01);
      box-shadow: 0 18px 36px rgba(0,0,0,.42), 0 0 24px rgba(139,92,246,.18) !important;
    }

    .value-box .value-box-title {
      color: #D9E6FF !important;
      font-weight: 650 !important;
    }

    .value-box .value-box-value {
      color: #FFFFFF !important;
      font-size: 29px !important;
      font-weight: 850 !important;
      text-shadow: 0 0 18px rgba(255,255,255,.12);
    }

    .value-box .value-box-showcase {
      color: rgba(255,255,255,.30) !important;
    }

    .sidebar {
      background: linear-gradient(160deg, rgba(10,31,58,.98), rgba(18,23,61,.98)) !important;
      border: 1px solid rgba(94,164,255,.20) !important;
      border-radius: 18px !important;
      color: var(--text) !important;
      box-shadow: 0 12px 30px rgba(0,0,0,.30) !important;
    }

    .sidebar .form-label,
    .sidebar label,
    .sidebar h5,
    .sidebar h6 {
      color: #EAF2FF !important;
      font-weight: 700 !important;
    }

    .sidebar .text-muted {
      color: var(--muted) !important;
    }

    .form-control, .selectize-input, .selectize-control.single .selectize-input {
      background: rgba(4,18,38,.92) !important;
      color: #EAF2FF !important;
      border: 1px solid rgba(100,149,237,.35) !important;
      border-radius: 11px !important;
      box-shadow: inset 0 1px 6px rgba(0,0,0,.20) !important;
    }

    .form-control:focus, .selectize-input.focus {
      border-color: #8B5CF6 !important;
      box-shadow: 0 0 0 3px rgba(139,92,246,.18), 0 0 18px rgba(139,92,246,.18) !important;
    }

    .selectize-dropdown {
      background: #0B1B34 !important;
      color: #EAF2FF !important;
      border: 1px solid rgba(139,92,246,.35) !important;
    }

    .selectize-dropdown .option:hover,
    .selectize-dropdown .active {
      background: rgba(108,99,255,.30) !important;
      color: #FFFFFF !important;
    }

    .btn {
      border-radius: 11px !important;
      font-weight: 700 !important;
      transition: all .2s ease !important;
    }

    .btn:hover {
      transform: translateY(-2px);
      box-shadow: 0 8px 20px rgba(108,99,255,.25);
    }

    .table {
      color: #EAF2FF !important;
      --bs-table-bg: transparent !important;
      --bs-table-color: #EAF2FF !important;
      border-color: rgba(255,255,255,.10) !important;
    }

    .table thead th {
      background: linear-gradient(90deg, #312E81, #4C1D95) !important;
      color: #FFFFFF !important;
      border-color: rgba(255,255,255,.12) !important;
    }

    .table tbody tr {
      background: rgba(11,31,58,.70) !important;
    }

    .table tbody tr:hover {
      background: rgba(108,99,255,.16) !important;
    }

    .text-muted {
      color: var(--muted) !important;
    }

    hr {
      border-color: rgba(139,92,246,.20) !important;
    }

    .nav-tabs .nav-link {
      color: #B8C9E4 !important;
    }

    .nav-tabs .nav-link.active {
      background: rgba(108,99,255,.18) !important;
      color: #FFFFFF !important;
      border-color: rgba(139,92,246,.45) !important;
    }

    .bslib-grid {
      row-gap: 18px !important;
    }

    .hero-panel {
      padding: 24px 28px;
      border-radius: 22px;
      background:
        radial-gradient(circle at 85% 30%, rgba(56,189,248,.18), transparent 25%),
        linear-gradient(120deg, rgba(16,44,83,.98), rgba(35,16,75,.94));
      border: 1px solid rgba(99,102,241,.42);
      box-shadow: 0 18px 40px rgba(0,0,0,.34), inset 0 1px 0 rgba(255,255,255,.05);
      margin-bottom: 18px;
    }

    .hero-title {
      font-size: 30px;
      font-weight: 850;
      background: linear-gradient(90deg, #FFFFFF, #A78BFA, #38BDF8);
      -webkit-background-clip: text;
      background-clip: text;
      color: transparent;
      margin: 0;
    }

    .hero-subtitle {
      color: #B9CBE7;
      font-size: 15px;
      margin-top: 7px;
    }

    .section-title {
      color: #F4F7FF;
      font-weight: 800;
      margin: 0 0 4px 0;
    }

    .glow-line {
      height: 3px;
      width: 90px;
      border-radius: 99px;
      background: linear-gradient(90deg, #8B5CF6, #22D3EE);
      box-shadow: 0 0 15px rgba(34,211,238,.45);
      margin-bottom: 14px;
    }

    .risk-low { color: #20E3B2 !important; }
    .risk-medium { color: #FBBF24 !important; }
    .risk-high { color: #FB5B7A !important; }

    .prediction-glow {
      border-radius: 18px;
      padding: 22px;
      background: linear-gradient(135deg, rgba(49,46,129,.35), rgba(14,116,144,.18));
      border: 1px solid rgba(99,102,241,.35);
      box-shadow: 0 0 28px rgba(99,102,241,.12);
    }

    .info-chip {
      display: inline-block;
      padding: 7px 11px;
      border-radius: 999px;
      margin: 3px;
      color: #DDE8FF;
      background: rgba(108,99,255,.14);
      border: 1px solid rgba(139,92,246,.30);
      font-size: 12px;
      font-weight: 650;
    }

    .small-note {
      color: #9FB2CF;
      font-size: 12px;
      line-height: 1.5;
    }

    .plotly {
      border-radius: 14px !important;
    }
  "))
)

# ==============================================================================
# UI DEFINITION
# ==============================================================================
# ==============================================================================
# UI DEFINITION
# ==============================================================================
ui <- tagList(
  dark_css,
  page_navbar(
  theme = custom_theme,
  title = span(
    icon("shield-halved", style = "margin-right: 8px; color: #18bc9c;"),
    "Crime Pattern Analysis & Crime Risk Prediction in India"
  ),
  navbar_options = navbar_options(collapsible = TRUE),
  
  # ----------------------------------------------------------------------------
  # TAB 1: HOME / DASHBOARD OVERVIEW
  # ----------------------------------------------------------------------------
  nav_panel(
    title = "Dashboard",
    icon = icon("gauge-high"),
    layout_column_wrap(
      width = 1,
      div(
        class = "hero-panel",
        div(class = "hero-title", icon("shield-halved"), " Crime Pattern Analysis & Crime Risk Prediction"),
        div(class = "hero-subtitle", "District-level insights • 2014–2023 • Temporal next-year risk prediction using R"),
        div(
          span(class = "info-chip", "30,000 Records"),
          span(class = "info-chip", "12 States"),
          span(class = "info-chip", "300 Districts"),
          span(class = "info-chip", "Decision Tree + Random Forest"),
          span(class = "info-chip", "R Shiny")
        )
      )
    ),
    
    # Value KPI Cards
    layout_column_wrap(
      width = 1/6,
      value_box(
        title = "Total Records",
        value = format(nrow(cleaned_data), big.mark = ","),
        showcase = icon("database"),
        theme = "primary"
      ),
      value_box(
        title = "States Covered",
        value = length(unique(cleaned_data$State)),
        showcase = icon("map-location-dot"),
        theme = "info"
      ),
      value_box(
        title = "Districts Covered",
        value = length(unique(cleaned_data$District)),
        showcase = icon("building-columns"),
        theme = "secondary"
      ),
      value_box(
        title = "Years Covered",
        value = "2014 – 2023",
        showcase = icon("calendar-days"),
        theme = "warning"
      ),
      value_box(
        title = "Total Cases Reported",
        value = paste0(round(sum(cleaned_data$Cases_Reported) / 10000000, 2), " Cr"),
        showcase = icon("file-invoice-dollar"),
        theme = "danger"
      ),
      value_box(
        title = "Avg Crime Rate / 100k",
        value = round(mean(cleaned_data$Crime_Rate_per_100k), 2),
        showcase = icon("chart-line"),
        theme = "success"
      )
    ),
    
    layout_column_wrap(
      width = 1/3,
      card(
        card_header(h5(icon("chart-line"), " Annual Reported Crime Cases", class = "mb-0")),
        card_body(plotlyOutput("home_cases_plot", height = "330px"))
      ),
      card(
        card_header(h5(icon("ranking-star"), " Top 10 States by Average Crime Rate", class = "mb-0")),
        card_body(plotlyOutput("home_states_plot", height = "330px"))
      ),
      card(
        card_header(h5(icon("chart-pie"), " Crime Risk Distribution", class = "mb-0")),
        card_body(plotlyOutput("home_risk_plot", height = "330px"))
      )
    )
  ),
  
  # ----------------------------------------------------------------------------
  # TAB 2: CRIME TRENDS
  # ----------------------------------------------------------------------------
  nav_panel(
    title = "Crime Trends",
    icon = icon("chart-line"),
    layout_sidebar(
      sidebar = sidebar(
        title = "Filter Controls",
        selectInput(
          "trends_state_filter",
          "Select State:",
          choices = c("All States", sort(unique(cleaned_data$State))),
          selected = "All States"
        ),
        hr(),
        p(class = "text-muted", "Select a specific state to inspect localized annual case counts and rate trajectories.")
      ),
      layout_column_wrap(
        width = 1/2,
        card(
          card_header("Annual Reported Crime Cases"),
          card_body(plotlyOutput("trends_cases_plot", height = "400px"))
        ),
        card(
          card_header("Average Crime Rate per 100k Population"),
          card_body(plotlyOutput("trends_rate_plot", height = "400px"))
        )
      )
    )
  ),
  
  # ----------------------------------------------------------------------------
  # TAB 3: CRIME TYPES
  # ----------------------------------------------------------------------------
  nav_panel(
    title = "Crime Types",
    icon = icon("list-check"),
    layout_sidebar(
      sidebar = sidebar(
        title = "Category Controls",
        selectInput(
          "crime_type_filter",
          "Select Specific Crime Category:",
          choices = c("All Crime Types", sort(unique(cleaned_data$Crime_Type))),
          selected = "All Crime Types"
        ),
        hr(),
        p(class = "text-muted", "Analyzes the 10 tracked crime categories across district observations.")
      ),
      layout_column_wrap(
        width = 1/2,
        card(
          card_header("Total Cases Reported by Crime Category"),
          card_body(plotlyOutput("crime_type_dist_plot", height = "380px"))
        ),
        card(
          card_header("Annual Trend by Crime Category"),
          card_body(plotlyOutput("crime_type_trend_plot", height = "380px"))
        )
      ),
      card(
        card_header("Crime Category Summary Statistics Table"),
        card_body(tableOutput("crime_type_summary_table"))
      )
    )
  ),
  
  # ----------------------------------------------------------------------------
  # TAB 4: RISK ANALYSIS
  # ----------------------------------------------------------------------------
  nav_panel(
    title = "Risk Analysis",
    icon = icon("triangle-exclamation"),
    layout_sidebar(
      sidebar = sidebar(
        title = "Risk Filters",
        selectInput(
          "risk_state_filter",
          "Select State:",
          choices = c("All States", sort(unique(cleaned_data$State))),
          selected = "All States"
        ),
        checkboxGroupInput(
          "risk_category_filter",
          "Select Risk Tiers:",
          choices = c("Low", "Medium", "High"),
          selected = c("Low", "Medium", "High")
        )
      ),
      layout_column_wrap(
        width = 1/2,
        card(
          card_header("Risk Category Share"),
          card_body(plotlyOutput("risk_pie_plot", height = "380px"))
        ),
        card(
          card_header("State-wise Crime Risk Breakdown"),
          card_body(plotlyOutput("risk_state_bar_plot", height = "380px"))
        )
      ),
      card(
        card_header("Highest Risk District Observations"),
        card_body(tableOutput("high_risk_districts_table"))
      )
    )
  ),
  
  # ----------------------------------------------------------------------------
  # TAB 5: NEXT-YEAR PREDICTION (INTERACTIVE DEMO)
  # ----------------------------------------------------------------------------
  nav_panel(
    title = "Next-Year Prediction",
    icon = icon("lightbulb"),
    layout_sidebar(
      sidebar = sidebar(
        title = "Prediction Selector",
        h6("2023 Crime Risk Prediction from 2022 Data", class = "text-primary font-weight-bold"),
        p(class = "text-muted small", "Select a 2022 district record to evaluate real 2023 risk prediction from the trained Random Forest model."),
        selectInput("pred_state", "Select State:", choices = sort(unique(predictions_data$State)), selected = "Uttar Pradesh"),
        uiOutput("pred_district_ui"),
        uiOutput("pred_crime_type_ui")
      ),
      card(
        card_header(
          class = "bg-primary text-white",
          h5(icon("bolt"), " Interactive Next-Year Prediction Result", class = "mb-0")
        ),
        card_body(
          uiOutput("prediction_result_card")
        )
      ),
      card(
        card_header("Held-Out Test Set Predictions (Year 2023 Targets)"),
        card_body(
          div(style = "overflow-x: auto; max-height: 400px;", tableOutput("predictions_preview_table"))
        )
      )
    )
  ),
  
  # ----------------------------------------------------------------------------
  # TAB 6: MODEL PERFORMANCE & METHODOLOGY
  # ----------------------------------------------------------------------------
  nav_panel(
    title = "Model Performance",
    icon = icon("award"),
    layout_column_wrap(
      width = 1,
      card(
        card_header(class = "bg-primary text-white", h5("Zero-Leakage Chronological Evaluation Results", class = "mb-0")),
        card_body(
          p("Below are the actual test evaluation results obtained by training models on ", strong("2014-2021 data"), " and testing on ", strong("held-out 2022 predictor data (predicting 2023 target risk)"), ":"),
          tableOutput("model_results_table")
        )
      )
    ),
    layout_column_wrap(
      width = 1/2,
      card(
        card_header("Decision Tree Rules (Graphs/15_decision_tree.png)"),
        card_body(tags$img(src = "Graphs/15_decision_tree.png", style = "width: 100%; height: auto; border-radius: 6px;"))
      ),
      card(
        card_header("Random Forest Feature Importance (Graphs/16_variable_importance.png)"),
        card_body(tags$img(src = "Graphs/16_variable_importance.png", style = "width: 100%; height: auto; border-radius: 6px;"))
      )
    )
  )
)
)


# Shared Plotly dark styling
dark_plot <- function(x) {
  x %>%
    layout(
      paper_bgcolor = "rgba(0,0,0,0)",
      plot_bgcolor = "#0B1B34",
      font = list(color = "#DDE8FF", family = "Inter"),
      margin = list(l = 55, r = 25, t = 35, b = 55),
      hoverlabel = list(
        bgcolor = "#111F3D",
        bordercolor = "#8B5CF6",
        font = list(color = "#FFFFFF")
      ),
      xaxis = list(
        gridcolor = "#20395E",
        zerolinecolor = "#284568",
        color = "#BFD0EA"
      ),
      yaxis = list(
        gridcolor = "#20395E",
        zerolinecolor = "#284568",
        color = "#BFD0EA"
      )
    ) %>%
    config(displaylogo = FALSE, modeBarButtonsToRemove = c("lasso2d", "select2d"))
}

# ==============================================================================
# SERVER LOGIC
# ==============================================================================
server <- function(input, output, session) {
  
  # ----------------------------------------------------------------------------
  # TAB 1: DASHBOARD HOME PLOTS
  # ----------------------------------------------------------------------------
  output$home_cases_plot <- renderPlotly({
    df <- cleaned_data %>%
      group_by(Year) %>%
      summarise(Total_Cases = sum(Cases_Reported), .groups = "drop")

    p <- ggplot(
      df,
      aes(
        x = Year,
        y = Total_Cases / 100000,
        text = paste(
          "<b>Year:</b>", Year,
          "<br><b>Reported Cases:</b>", format(Total_Cases, big.mark = ",")
        )
      )
    ) +
      geom_area(fill = "#6C63FF", alpha = .18) +
      geom_line(color = "#A78BFA", linewidth = 1.4) +
      geom_point(color = "#38BDF8", size = 3.2) +
      scale_x_continuous(breaks = 2014:2023) +
      labs(x = "Year", y = "Cases Reported (Lakhs)") +
      theme_minimal(base_size = 12) +
      theme(
        panel.background = element_rect(fill = "#0B1B34", colour = NA),
        plot.background = element_rect(fill = "#0B1B34", colour = NA),
        panel.grid.major = element_line(colour = "#20395E"),
        panel.grid.minor = element_blank(),
        axis.text = element_text(colour = "#BFD0EA"),
        axis.title = element_text(colour = "#DDE8FF", face = "bold")
      )

    dark_plot(ggplotly(p, tooltip = "text"))
  })

  output$home_states_plot <- renderPlotly({
    df <- cleaned_data %>%
      group_by(State) %>%
      summarise(Avg_Rate = mean(Crime_Rate_per_100k), .groups = "drop") %>%
      arrange(desc(Avg_Rate)) %>%
      head(10)

    p <- ggplot(
      df,
      aes(
        x = reorder(State, Avg_Rate),
        y = Avg_Rate,
        text = paste("<b>State:</b>", State, "<br><b>Average Rate:</b>", round(Avg_Rate, 2))
      )
    ) +
      geom_col(fill = "#8B5CF6", width = .72) +
      coord_flip() +
      labs(x = NULL, y = "Average Crime Rate / 100k") +
      theme_minimal(base_size = 12) +
      theme(
        panel.background = element_rect(fill = "#0B1B34", colour = NA),
        plot.background = element_rect(fill = "#0B1B34", colour = NA),
        panel.grid.major = element_line(colour = "#20395E"),
        panel.grid.minor = element_blank(),
        axis.text = element_text(colour = "#BFD0EA"),
        axis.title = element_text(colour = "#DDE8FF", face = "bold")
      )

    dark_plot(ggplotly(p, tooltip = "text"))
  })

  output$home_risk_plot <- renderPlotly({
    df <- cleaned_data %>%
      count(Crime_Risk)

    plot_ly(
      df,
      labels = ~Crime_Risk,
      values = ~n,
      type = "pie",
      hole = .58,
      textinfo = "label+percent",
      marker = list(
        colors = c("Low" = "#20E3B2", "Medium" = "#FBBF24", "High" = "#FB5B7A"),
        line = list(color = "#071426", width = 3)
      )
    ) %>%
      dark_plot() %>%
      layout(
        showlegend = TRUE,
        legend = list(font = list(color = "#DDE8FF")),
        margin = list(l = 10, r = 10, t = 10, b = 10)
      )
  })

  # ----------------------------------------------------------------------------
  # TAB 2: CRIME TRENDS LOGIC
  # ----------------------------------------------------------------------------
  filtered_trends_data <- reactive({
    if (input$trends_state_filter == "All States") {
      cleaned_data
    } else {
      cleaned_data %>% filter(State == input$trends_state_filter)
    }
  })
  
  output$trends_cases_plot <- renderPlotly({
    df <- filtered_trends_data() %>%
      group_by(Year) %>%
      summarise(Total_Cases = sum(Cases_Reported), .groups = "drop")
    
    p <- ggplot(df, aes(x = Year, y = Total_Cases / 100000, text = paste("Year:", Year, "<br>Cases:", format(Total_Cases, big.mark=",")))) +
      geom_line(color = "#8B5CF6", linewidth = 1.35) +
      geom_point(color = "#38BDF8", size = 3.2) +
      scale_x_continuous(breaks = 2014:2023) +
      labs(x = "Year", y = "Cases Reported (Lakhs)") +
      theme_minimal(base_size = 12) + theme(panel.background = element_rect(fill = "#0B1B34", colour = NA), plot.background = element_rect(fill = "#0B1B34", colour = NA), panel.grid.major = element_line(colour = "#20395E"), panel.grid.minor = element_blank(), axis.text = element_text(colour = "#BFD0EA"), axis.title = element_text(colour = "#DDE8FF", face = "bold"), legend.background = element_rect(fill = "#0B1B34", colour = NA), legend.text = element_text(colour = "#DDE8FF"))
    
    dark_plot(ggplotly(p, tooltip = "text"))
  })
  
  output$trends_rate_plot <- renderPlotly({
    df <- filtered_trends_data() %>%
      group_by(Year) %>%
      summarise(Avg_Rate = mean(Crime_Rate_per_100k), .groups = "drop")
    
    p <- ggplot(df, aes(x = Year, y = Avg_Rate, text = paste("Year:", Year, "<br>Avg Rate:", round(Avg_Rate, 2)))) +
      geom_line(color = "#FB5B9A", linewidth = 1.35) +
      geom_point(color = "#FBBF24", size = 3.2) +
      scale_x_continuous(breaks = 2014:2023) +
      labs(x = "Year", y = "Average Crime Rate / 100k") +
      theme_minimal(base_size = 12) + theme(panel.background = element_rect(fill = "#0B1B34", colour = NA), plot.background = element_rect(fill = "#0B1B34", colour = NA), panel.grid.major = element_line(colour = "#20395E"), panel.grid.minor = element_blank(), axis.text = element_text(colour = "#BFD0EA"), axis.title = element_text(colour = "#DDE8FF", face = "bold"), legend.background = element_rect(fill = "#0B1B34", colour = NA), legend.text = element_text(colour = "#DDE8FF"))
    
    dark_plot(ggplotly(p, tooltip = "text"))
  })
  
  # ----------------------------------------------------------------------------
  # TAB 3: CRIME TYPES LOGIC
  # ----------------------------------------------------------------------------
  output$crime_type_dist_plot <- renderPlotly({
    df <- cleaned_data %>%
      group_by(Crime_Type) %>%
      summarise(Total_Cases = sum(Cases_Reported), .groups = "drop") %>%
      arrange(desc(Total_Cases))
    
    p <- ggplot(df, aes(x = reorder(Crime_Type, Total_Cases), y = Total_Cases / 100000, fill = Crime_Type)) +
      geom_col(show.legend = FALSE) +
      coord_flip() +
      labs(x = "Crime Category", y = "Total Cases (Lakhs)") +
      theme_minimal(base_size = 12) + theme(panel.background = element_rect(fill = "#0B1B34", colour = NA), plot.background = element_rect(fill = "#0B1B34", colour = NA), panel.grid.major = element_line(colour = "#20395E"), panel.grid.minor = element_blank(), axis.text = element_text(colour = "#BFD0EA"), axis.title = element_text(colour = "#DDE8FF", face = "bold"), legend.background = element_rect(fill = "#0B1B34", colour = NA), legend.text = element_text(colour = "#DDE8FF"))
    
    dark_plot(ggplotly(p))
  })
  
  output$crime_type_trend_plot <- renderPlotly({
    df <- cleaned_data
    if (input$crime_type_filter != "All Crime Types") {
      df <- df %>% filter(Crime_Type == input$crime_type_filter)
    }
    
    trend_df <- df %>%
      group_by(Year, Crime_Type) %>%
      summarise(Total_Cases = sum(Cases_Reported), .groups = "drop")
    
    p <- ggplot(trend_df, aes(x = Year, y = Total_Cases / 1000, color = Crime_Type)) +
      geom_line(linewidth = 1) +
      scale_x_continuous(breaks = 2014:2023) +
      labs(x = "Year", y = "Cases Reported (Thousands)") +
      theme_minimal(base_size = 12) + theme(panel.background = element_rect(fill = "#0B1B34", colour = NA), plot.background = element_rect(fill = "#0B1B34", colour = NA), panel.grid.major = element_line(colour = "#20395E"), panel.grid.minor = element_blank(), axis.text = element_text(colour = "#BFD0EA"), axis.title = element_text(colour = "#DDE8FF", face = "bold"), legend.background = element_rect(fill = "#0B1B34", colour = NA), legend.text = element_text(colour = "#DDE8FF"))
    
    dark_plot(ggplotly(p))
  })
  
  output$crime_type_summary_table <- renderTable({
    cleaned_data %>%
      group_by(`Crime Type` = Crime_Type) %>%
      summarise(
        `Total Cases Reported` = format(sum(Cases_Reported), big.mark = ","),
        `Total Convictions` = format(sum(Convictions), big.mark = ","),
        `Avg Conviction Rate (%)` = paste0(round(mean(Conviction_Rate) * 100, 2), "%"),
        `Avg Chargesheet Rate (%)` = paste0(round(mean(Chargesheet_Rate) * 100, 2), "%")
      )
  }, striped = TRUE, hover = TRUE, bordered = TRUE)
  
  # ----------------------------------------------------------------------------
  # TAB 4: RISK ANALYSIS LOGIC
  # ----------------------------------------------------------------------------
  output$risk_pie_plot <- renderPlotly({
    df <- cleaned_data %>%
      filter(Crime_Risk %in% input$risk_category_filter) %>%
      group_by(Crime_Risk) %>%
      summarise(Count = n(), .groups = "drop")
    
    plot_ly(df, labels = ~Crime_Risk, values = ~Count, type = "pie",
            marker = list(colors = c("Low" = "#20E3B2", "Medium" = "#FBBF24", "High" = "#FB5B7A"), line = list(color = "#071426", width = 2)))
  })
  
  output$risk_state_bar_plot <- renderPlotly({
    df <- cleaned_data %>%
      filter(Crime_Risk %in% input$risk_category_filter)
    
    if (input$risk_state_filter != "All States") {
      df <- df %>% filter(State == input$risk_state_filter)
    }
    
    summary_df <- df %>%
      group_by(State, Crime_Risk) %>%
      summarise(Count = n(), .groups = "drop")
    
    p <- ggplot(summary_df, aes(x = State, y = Count, fill = Crime_Risk)) +
      geom_col(position = "stack") +
      scale_fill_manual(values = c("Low" = "#20E3B2", "Medium" = "#FBBF24", "High" = "#FB5B7A")) +
      theme_minimal(base_size = 12) + theme(panel.background = element_rect(fill = "#0B1B34", colour = NA), plot.background = element_rect(fill = "#0B1B34", colour = NA), panel.grid.major = element_line(colour = "#20395E"), panel.grid.minor = element_blank(), axis.text = element_text(colour = "#BFD0EA"), axis.title = element_text(colour = "#DDE8FF", face = "bold"), legend.background = element_rect(fill = "#0B1B34", colour = NA), legend.text = element_text(colour = "#DDE8FF")) +
      theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
      labs(x = "State", y = "Record Count")
    
    dark_plot(ggplotly(p))
  })
  
  output$high_risk_districts_table <- renderTable({
    cleaned_data %>%
      filter(Crime_Risk == "High") %>%
      group_by(State, District) %>%
      summarise(
        `Avg Crime Rate / 100k` = round(mean(Crime_Rate_per_100k), 2),
        `Total Cases` = format(sum(Cases_Reported), big.mark = ","),
        `Avg Population` = format(round(mean(Population)), big.mark = ","),
        .groups = "drop"
      ) %>%
      arrange(desc(`Avg Crime Rate / 100k`)) %>%
      head(10)
  }, striped = TRUE, hover = TRUE, bordered = TRUE)
  
  # ----------------------------------------------------------------------------
  # TAB 5: NEXT-YEAR PREDICTION LOGIC
  # ----------------------------------------------------------------------------
  output$pred_district_ui <- renderUI({
    districts <- predictions_data %>%
      filter(State == input$pred_state) %>%
      pull(District) %>%
      unique() %>%
      sort()
    selectInput("pred_district", "Select District:", choices = districts)
  })
  
  output$pred_crime_type_ui <- renderUI({
    req(input$pred_district)
    crime_types <- predictions_data %>%
      filter(State == input$pred_state, District == input$pred_district) %>%
      pull(Crime_Type) %>%
      unique() %>%
      sort()
    selectInput("pred_crime_type", "Select Crime Type:", choices = crime_types)
  })
  
  selected_prediction <- reactive({
    req(input$pred_state, input$pred_district, input$pred_crime_type)
    predictions_data %>%
      filter(
        State == input$pred_state,
        District == input$pred_district,
        Crime_Type == input$pred_crime_type
      ) %>%
      head(1)
  })
  
  output$prediction_result_card <- renderUI({
    res <- selected_prediction()
    if (nrow(res) == 0) {
      return(div(class = "alert alert-warning", "No prediction record found for the selected inputs."))
    }
    
    match_color <- if (res$Match == "Correct") "#2ecc71" else "#e74c3c"
    match_icon  <- if (res$Match == "Correct") "check-circle" else "times-circle"
    
    tagList(
      div(
        class = "row text-center my-3",
        div(
          class = "col-md-3",
          div(class = "p-3 border rounded prediction-glow",
              h6("Predictor Year (Data)", class = "text-muted mb-1"),
              h4(res$Predictor_Year, class = "text-dark font-weight-bold"))
        ),
        div(
          class = "col-md-3",
          div(class = "p-3 border rounded prediction-glow",
              h6("Target Year (Forecast)", class = "text-muted mb-1"),
              h4(res$Target_Year, class = "text-dark font-weight-bold"))
        ),
        div(
          class = "col-md-3",
          div(class = "p-3 border rounded prediction-glow",
              h6("Actual 2023 Risk", class = "text-muted mb-1"),
              span(class = "badge fs-5 px-3 py-2", 
                   style = paste0("background-color:", switch(res$Actual_Next_Year_Risk, "Low"="#2ecc71", "Medium"="#f39c12", "High"="#e74c3c")),
                   res$Actual_Next_Year_Risk))
        ),
        div(
          class = "col-md-3",
          div(class = "p-3 border rounded bg-light",
              h6("Predicted 2023 Risk", class = "text-muted mb-1"),
              span(class = "badge fs-5 px-3 py-2", 
                   style = paste0("background-color:", switch(res$Predicted_Next_Year_Risk, "Low"="#2ecc71", "Medium"="#f39c12", "High"="#e74c3c")),
                   res$Predicted_Next_Year_Risk))
        )
      ),
      hr(),
      div(
        class = "d-flex justify-content-between align-items-center p-3 rounded text-white",
        style = paste0("background-color: ", match_color, ";"),
        div(
          h5(icon(match_icon), " Prediction Status: ", res$Match, class = "mb-0")
        ),
        div(
          span(class = "small", sprintf("2022 Cases Reported: %s | District Population: %s", 
                                       format(res$Cases_Reported, big.mark=","), 
                                       format(res$Population, big.mark=",")))
        )
      )
    )
  })
  
  output$predictions_preview_table <- renderTable({
    predictions_data %>%
      select(
        State, District, `Predictor Year` = Predictor_Year, 
        `Target Year` = Target_Year, `Crime Type` = Crime_Type, 
        `2022 Cases` = Cases_Reported, `Actual Risk (2023)` = Actual_Next_Year_Risk, 
        `Predicted Risk (2023)` = Predicted_Next_Year_Risk, Match
      ) %>%
      head(20)
  }, striped = TRUE, hover = TRUE, bordered = TRUE)
  
  # ----------------------------------------------------------------------------
  # TAB 6: MODEL PERFORMANCE LOGIC
  # ----------------------------------------------------------------------------
  output$model_results_table <- renderTable({
    model_results %>%
      mutate(
        `Accuracy (%)` = paste0(round(Accuracy * 100, 2), "%"),
        Precision = sprintf("%.4f", Precision),
        Recall = sprintf("%.4f", Recall),
        `F1 Score` = sprintf("%.4f", F1_Score)
      ) %>%
      select(Model, `Accuracy (%)`, Precision, Recall, `F1 Score`)
  }, striped = TRUE, hover = TRUE, bordered = TRUE)
}

# Run Shiny Application
shinyApp(ui = ui, server = server)
